### ISSUE TITLE
turbo-client启动报错，能帮忙解决下吗

### ISSUE THREAD

**Issue by sy-duminjun** [didi/turbo#34]
TypeError: Cannot read properties of undefined (reading 'configure')
    at D:\ideaworkspace\turbo-client\node_modules\vite\dist\node\chunks\dep-971d9e33.js:51435:18
    at Array.forEach (<anonymous>)
    at proxyMiddleware (D:\ideaworkspace\turbo-client\node_modules\vite\dist\node\chunks\dep-971d9e33.js:51423:26)
    at createServer (D:\ideaworkspace\turbo-client\node_modules\vite\dist\node\chunks\dep-971d9e33.js:56584:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CAC.<anonymous> (D:\ideaworkspace\turbo-client\node_modules\vite\dist\node\cli.js:688:24)

**Comment by namelessyy** [comment]
把.env.development中的 VITE_SERVER_ADDR 注释放开
